version: "{build}"

image:
  - Visual Studio 2017

platform: x64

environment:
  nodejs_version: $env:NODEJS_VERSION
  APPVEYOR_RDP_PASSWORD: $env:APPVEYOR_RDP_PASSWORD
  REPO_DIR: $env:REPO_DIR
  DESKTOP_DIR: $env:DESKTOP_DIR
  ZIMBRA_PROXY_URL: $env:ZIMBRA_PROXY_URL
  SERVER_ADMIN_USERNAME: $env:SERVER_ADMIN_USERNAME
  SERVER_ADMIN_PASSWORD: $env:SERVER_ADMIN_PASSWORD
  TEST_SUITE: $env:TEST_SUITE
  HTML_REPORT_PATH: $env:HTML_REPORT_PATH

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: Install-Product node $env:nodejs_version

install:
  - ps: cd $env:DESKTOP_DIR
  - ps: New-Item -ItemType SymbolicLink -Name appveyor-desktop -Target C:\projects\appveyor-desktop
  - ps: Remove-Item .\Tools , '.\Visual Studio 2015.lnk' , '.\Visual Studio 2017.lnk' -Recurse -Force
  - ps: Start-FileDownload https://52616-126518968-gh.circle-artifacts.com/0/electron/Zimbra_X_Desktop_0.0.1_e8e01cc_20190426094759.exe?circle-token=15147e283947071011540e2f26a74bcd7b002c6f

build_script:
  - ps: Start-Process .\Zimbra_X_Desktop_0.0.1_e8e01cc_20190426094759.exe /S -NoNewWindow -Wait -PassThru  

test_script:
  - ps: cd $env:REPO_DIR
  - ps: npm install
  - ps: npm install -g --save-dev mocha spectron
  - cmd: set SERVER_ADMIN_USERNAME=$env:SERVER_ADMIN_USERNAME && SET SERVER_ADMIN_PASSWORD=$env:SERVER_ADMIN_PASSWORD && SET TEST_SUITE=$env:TEST_SUITE && mocha tests/spectron/conf/configure.js
  - cmd: set ZIMBRA_PROXY_URL=$env:ZIMBRA_PROXY_URL && SET SERVER_ADMIN_USERNAME=$env:SERVER_ADMIN_USERNAME && SET SERVER_ADMIN_PASSWORD=$env:SERVER_ADMIN_PASSWORD && SET TEST_SUITE=$env:TEST_SUITE && SET HTML_REPORT_PATH=$env:test-reports/spectron && mocha --recursive tests\spectron\tests\mail -f Smoke --retries 1

artifacts:
  - path: test-reports
    name: result

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
