version: "{build}"

image:
  - Visual Studio 2017

platform: x64

environment:
  MSVC_DEFAULT_OPTIONS: ON

init:
  - cmd: cmake --version  

clone_folder: c:\projects\myproject

install:
  #------------------
  # Windows 10
  #------------------
  # update vcpkg
  - cmd: cd C:\tools\vcpkg
  - cmd: git pull
  - cmd: vcpkg install --recurse --triplet %VCPKG_ARCH% assimp boost-system boost-filesystem ccd eigen3 fcl
  - cmd: vcpkg integrate install
  - cmd: cd "%APPVEYOR_BUILD_FOLDER%"

build_script:
  #------------------
  # Windows 10
  #------------------
  - cmd: mkdir build && cd build  