version: "{build}"

image:
  - Visual Studio 2017

platform: x64

environment:
  MSVC_DEFAULT_OPTIONS: ON
  nodejs_version: "11.0.0"

init:
  - ps: Install-Product node $env:nodejs_version

install:
  - ps: Start-FileDownload 'https://zimbraqa.s3.ap-south-1.amazonaws.com/CircleCI/Zimbra_X_Desktop_0.0.1_e8e01cc_20190426094759.exe'
  - ps: Start-Process 'Zimbra_X_Desktop_0.0.1_e8e01cc_20190426094759.exe /S' -PassThru
  
test_script:
  - node --version
  - npm --version  

build_script:
  - cmd: mkdir build && cd build
