version: "{build}"

image:
  - Visual Studio 2017

platform: x64

environment:
  MSVC_DEFAULT_OPTIONS: ON
  nodejs_version: "11.0.0"

init:
  - cmd: cmake --version  

clone_folder: c:\projects\myproject

install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm install
  - cmd: cd C:\tools\vcpkg
  - cmd: git pull
  - cmd: vcpkg install --recurse --triplet %VCPKG_ARCH% x64-windows boost-system boost-filesystem ccd eigen3 fcl
  - cmd: vcpkg integrate install
  - cmd: cd "%APPVEYOR_BUILD_FOLDER%"
  
test_script:
  - node --version
  - npm --version  

build_script:
  - cmd: mkdir build && cd build  
