version: "{build}"

image:
  - Visual Studio 2017

platform: x64

environment:
  MSVC_DEFAULT_OPTIONS: ON
  nodejs_version: "11.0.0"

init:
  - ps: Install-Product node $env:nodejs_version

install:
  - ps: Start-FileDownload 'https://zimbraqa.s3.ap-south-1.amazonaws.com/CircleCI/Zimbra_X_Desktop_0.0.1_e8e01cc_20190426094759.exe'
  - cmd: npm install
  - cmd: cd C:\tools\vcpkg
  - cmd: git pull
  - cmd: vcpkg install --recurse --triplet %VCPKG_ARCH% x64-windows boost-system boost-filesystem ccd eigen3 fcl
  - cmd: vcpkg integrate install    
  - ps: Start-Process .\Zimbra_X_Desktop_0.0.1_e8e01cc_20190426094759.exe /S -NoNewWindow -Wait -PassThru
  - ps: Start-Sleep -Seconds 10
  - ps: cd $env:APPDATA
  - ps: dir   

test_script:
  - node --version
  - npm --version  

build_script:
  - cmd: mkdir build && cd build
