version: {APPVEYOR_BUILD_VERSION}

image:
  - Visual Studio 2017

platform:
  - x64

environment:
  nodejs_version: $env:NODEJS_VERSION
  APPVEYOR_RDP_ENABLED: $env:APPVEYOR_RDP_ENABLED
  APPVEYOR_RDP_PASSWORD: $env:APPVEYOR_RDP_PASSWORD
  BUILD_NOTIFICATION_EMAIL: $env:BUILD_NOTIFICATION_EMAIL
  REPO_DIR: $env:REPO_DIR
  DESKTOP_DIR: $env:DESKTOP_DIR
  TEST_SUITE: $env:TEST_SUITE
  ZIMBRA_PROXY_URL: $env:ZIMBRA_PROXY_URL
  SERVER_ADMIN_USERNAME: $env:SERVER_ADMIN_USERNAME
  SERVER_ADMIN_PASSWORD: $env:SERVER_ADMIN_PASSWORD
  HTML_REPORT_PATH: $env:HTML_REPORT_PATH
  TEXT_REPORT_PATH: $env:TEXT_REPORT_PATH
  DESKTOP_BUILD_URL: https://52616-126518968-gh.circle-artifacts.com/0/electron/Zimbra_X_Desktop_0.0.1_e8e01cc_20190426094759.exe?circle-token=15147e283947071011540e2f26a74bcd7b002c6f

branches:
  only:
    - master

init:
  - ps: >-
        if ($env:APPVEYOR_RDP_ENABLED -eq 'TRUE') { 
          echo '----- Initiate remote desktop connection -----' 
          powershell -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))"
        } else { 
          echo '----- Remote desktop connection disabled -----' 
        }

before_build:
  - echo '----- Check out code and install nodejs -----'
  - ps: Install-Product node $env:nodejs_version

install:
  - echo '----- Download desktop build -----'
  - ps: cd $env:DESKTOP_DIR
  - ps: New-Item -ItemType SymbolicLink -Name appveyor-desktop -Target C:\projects\appveyor-desktop | out-null
  - ps: Remove-Item .\Tools , '.\Visual Studio 2015.lnk' , '.\Visual Studio 2017.lnk' -Recurse -Force
  - ps: $GET_DESKTOP_BUILD_FILE = $env:DESKTOP_BUILD_URL -split '/'
  - ps: $DESKTOP_BUILD_FILENAME = $GET_DESKTOP_BUILD_FILE[5] -split '\?'
  - ps: Start-FileDownload $env:DESKTOP_BUILD_URL

  - echo '----- Install desktop build -----'
  - ps: Start-Process -FilePath $DESKTOP_BUILD_FILENAME[0] /S -Wait -WindowStyle Maximized -PassThru

build_script:
  - echo '----- Build project code -----'
  - ps: cd $env:REPO_DIR
  - ps: npm install

  - echo '----- Install pre-requisites -----'
  - ps: npm install -g --save-dev mocha spectron mochawesome

before_test:
  - echo '----- Set screen resolution -----'
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))
  - ps: Set-ScreenResolution 1920 1080
 
test_script:
  - echo '----- Configure test suite -----'
  - ps: New-Item -ItemType Directory -Path $env:REPO_DIR\$env:HTML_REPORT_PATH -Force  | out-null
  - ps: Add-Content environment.txt "Set-Item Env:ZIMBRA_PROXY_URL $env:ZIMBRA_PROXY_URL ; Set-Item Env:SERVER_ADMIN_USERNAME $env:SERVER_ADMIN_USERNAME ; Set-Item Env:SERVER_ADMIN_PASSWORD $env:SERVER_ADMIN_PASSWORD ; Set-Item Env:TEST_SUITE $env:TEST_SUITE ; Set-Item Env:HTML_REPORT_PATH $env:HTML_REPORT_PATH ; Set-Item Env:TEXT_REPORT_PATH $env:TEXT_REPORT_PATH ; mocha --recursive tests\spectron\tests\mail -f $env:TEST_SUITE --retries 2 --no-deprecation --reporter mochawesome --reporter-options reportDir=$env:HTML_REPORT_PATH > $env:TEXT_REPORT_PATH"
  - ps: Set-Item Env:SERVER_ADMIN_USERNAME $env:SERVER_ADMIN_USERNAME ; Set-Item Env:SERVER_ADMIN_PASSWORD $env:SERVER_ADMIN_PASSWORD ; Set-Item Env:TEST_SUITE $env:TEST_SUITE ; mocha tests/spectron/conf/configure.js -f Configure

  - echo '----- Run desktop automation tests -----'
  - ps: Set-Item Env:ZIMBRA_PROXY_URL $env:ZIMBRA_PROXY_URL ; Set-Item Env:SERVER_ADMIN_USERNAME $env:SERVER_ADMIN_USERNAME ; Set-Item Env:SERVER_ADMIN_PASSWORD $env:SERVER_ADMIN_PASSWORD ; Set-Item Env:TEST_SUITE $env:TEST_SUITE ; Set-Item Env:HTML_REPORT_PATH $env:HTML_REPORT_PATH ; Set-Item Env:TEXT_REPORT_PATH $env:TEXT_REPORT_PATH ; mocha --recursive tests\spectron\tests\mail -f $env:TEST_SUITE --retries 2 --no-deprecation --reporter mochawesome --reporter-options reportDir=$env:HTML_REPORT_PATH > $env:TEXT_REPORT_PATH

artifacts:
  - path: test-reports\spectron
    name: ${APPVEYOR_REPO_BRANCH}-${APPVEYOR_BUILD_VERSION}
    
on_success:
  - ps: Add-AppveyorMessage "Tests passed"
  - ps: >-
      Get-Content README.md | Where-Object {$_ -match 'passing'} | ForEach-Object {
        powershell -Command "Add-AppveyorTest -Name Desktop -Framework Mocha -Filename report.txt -Outcome PASSED -Duration 0"
      }

on_failure:
  - ps: Add-AppveyorMessage "Tests failed"
  - ps: >-
      Get-Content README.md | Where-Object {$_ -match 'failing'} | ForEach-Object {
        powershell -Command "Add-AppveyorTest -Name Desktop -Framework Mocha -Filename report.txt -Outcome FAILED -Duration 0"
      }

on_finish:
  - echo '----- Test output -----'
  - ps: cat $env:TEXT_REPORT_PATH
  - ps: Push-AppveyorArtifact test-reports\{APPVEYOR_REPO_BRANCH}-${APPVEYOR_BUILD_VERSION}.zip

  - ps: >-
        if ($env:APPVEYOR_RDP_ENABLED -eq 'TRUE') { 
          echo '----- Close remote desktop connection -----'
          powershell -Command "$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))"
        }
