export const USER_ROOT_FOLDER_ID = '1';
export const USER_FOLDER_IDS = {
	ROOT: 1,
	INBOX: 2,
	TRASH: 3,
	JUNK: 4,
	SENT: 5,
	DRAFTS: 6,
	CONTACTS: 7,
	CALENDAR: 10,
	EMAILED_CONTACTS: 13,
	CHAT: 14,
	TASKS: 15
};
export const INTERNAL_GAL_PATH = '_InternalGAL';
